# Copyright 2023 Canonical Ltd.
# See LICENSE file for licensing details.
options:
  deployment-mode:
    default: "serverless"
    description: Deployment mode for kserve. It can only be RawDeployment or Serverless, and the latter requires knative-serving to be present in the model, and the local-gateway relation to be established.
    type: string
  domain-name:
    default: "example.com"
    description: The domain name used for all fully-qualified route names shown. In serverless mode, it has to be the same as knative-serving's domain name; otherwise, it can be changed to match the cluster ingress configuration.
    type: string
  port:
    type: int
    default: 9443
    description: Listening port
  custom_images:
    type: string
    default: | 
      configmap__agent : ''
      configmap__batcher : ''
      configmap__explainers__alibi : ''
      configmap__explainers__art : ''
      configmap__logger : ''
      configmap__router : ''
      configmap__storageInitializer : ''
      serving_runtimes__lgbserver : ''
      serving_runtimes__kserve_mlserver : ''
      serving_runtimes__paddleserver : ''
      serving_runtimes__pmmlserver : ''
      serving_runtimes__sklearnserver : ''
      serving_runtimes__tensorflow_serving : ''
      serving_runtimes__torchserve : ''
      serving_runtimes__tritonserver : ''
      serving_runtimes__xgbserver : ''
    description: >
      YAML or JSON formatted input defining images to use in Katib
      For usage details, see https://github.com/canonical/kserve-operators.

