#!/usr/bin/env python3
# Copyright 2026 Canonical Ltd.
# See LICENSE file for licensing details.

import json
import logging
from base64 import b64encode
from typing import Dict

import tenacity
import yaml
from charmed_kubeflow_chisme.exceptions import ErrorWithStatus, GenericCharmRuntimeError
from charmed_kubeflow_chisme.kubernetes import (
    KubernetesResourceHandler,
    create_charm_default_labels,
)
from charmed_kubeflow_chisme.lightkube.batch import delete_many
from charmed_kubeflow_chisme.pebble import update_layer
from charms.loki_k8s.v1.loki_push_api import LogForwarder
from charms.prometheus_k8s.v0.prometheus_scrape import MetricsEndpointProvider
from lightkube import ApiError, Client
from lightkube.core.exceptions import LoadResourceError
from lightkube.generic_resource import load_in_cluster_generic_resources
from lightkube.resources.apiextensions_v1 import CustomResourceDefinition
from ops import main
from ops.charm import CharmBase
from ops.framework import StoredState
from ops.model import (
    ActiveStatus,
    BlockedStatus,
    Container,
    MaintenanceStatus,
    ModelError,
    WaitingStatus,
)
from ops.pebble import APIError, Layer, PathError, ProtocolError

from certs import gen_certs

log = logging.getLogger(__name__)

DEFAULT_IMAGES_FILE = "src/default-custom-images.json"
with open(DEFAULT_IMAGES_FILE, "r") as json_file:
    DEFAULT_IMAGES = json.load(json_file)

BASE_RESOURCE_FILES = [
    "src/templates/crd_manifests.yaml.j2",
    "src/templates/auth_manifests.yaml.j2",
    "src/templates/webhook_manifests.yaml.j2",
]
SCHEDULER_CONFIG_FILES = ["src/templates/llmisvc_configs_manifests.yaml.j2"]
CONTAINER_CERTS_DEST = "/tmp/k8s-webhook-server/serving-certs/"
CONTROLLER_SYNC_RELATION = "kserve-controller"
LWS_SYNC_RELATION = "lws-controller"
METRICS_PORT = 8080
METRICS_PROXY_CONTAINER = "metrics-proxy"
METRICS_PROXY_PORT = 15090
METRICS_PROXY_SCRAPE_TIMEOUT = "9s"
# Label selector matching pods generated by LLMInferenceService workloads
# (vLLM workers and EPP schedulers both carry this label).
# Upstream reference (v0.17.0):
# https://github.com/kserve/kserve/blob/v0.17.0/config/llmisvcconfig/config-llm-scheduler.yaml
WORKLOAD_POD_LABEL_SELECTOR = "app.kubernetes.io/part-of=llminferenceservice"

KRH_SCOPE_BASE = "kserve-llmisvc-base"
KRH_SCOPE_SCHEDULER_CONFIG = "kserve-llmisvc-scheduler-config"

# The charm-managed controller attaches the `serving.kserve.io/llmisvc-finalizer`
# to LLMInferenceService CRs. Deleting the LLMInferenceService CRD while the
# controller is still running cascades deletion to all its CRs and lets the
# controller clear their finalizers; the CRD must be fully gone before the
# controller workload is torn down, otherwise the CRD (and its CRs) get stuck
# terminating.
# How long to wait for the CRD (and the CRs it cascades to) to be removed.
LLMISVC_DELETION_TIMEOUT = 300
LLMISVC_DELETION_POLL_INTERVAL = 5


def parse_images_config(config: str) -> Dict:
    """Parse yaml/json image overrides from config."""
    if not config:
        return {}
    try:
        images = yaml.safe_load(config)
    except yaml.YAMLError as err:
        msg = (
            f"Cannot parse a config-defined images list from config '{config}'"
            f". Got error: {err}"
        )
        raise ErrorWithStatus(msg, BlockedStatus) from err

    if images is None:
        return {}
    if not isinstance(images, dict):
        raise ErrorWithStatus("custom_images must be a YAML/JSON object", BlockedStatus)
    return images


# For errors when a K8s object exists while it shouldn't
class ObjectStillExistsError(Exception):
    """Exception for when a K8s object exists, while it should have been removed."""

    def __init__(self, resource_name: str):
        self.resource_name = resource_name


class KServeLLMISVCCharm(CharmBase):
    """Scheduler-first charm for the KServe llmisvc controller."""

    _stored = StoredState()

    def __init__(self, *args):
        super().__init__(*args)

        self.custom_images = {}
        self.images_context = {}

        self._base_resource_handler = None
        self._scheduler_config_resource_handler = None
        self._lightkube_field_manager = "lightkube"

        self._controller_container_name = "llmisvc-controller"
        self._controller_service_name = self.app.name
        self._webhook_service_name = "llmisvc-webhook-server-service"
        self.controller_container = self.unit.get_container(self._controller_container_name)
        self.metrics_proxy_container = self.unit.get_container(METRICS_PROXY_CONTAINER)

        self._gen_certs_if_missing()

        self._logging = LogForwarder(charm=self)

        for event in [
            self.on.install,
            self.on.config_changed,
            self.on.llmisvc_controller_pebble_ready,
            self.on.metrics_proxy_pebble_ready,
            self.on.leader_elected,
            self.on.update_status,
            self.on[CONTROLLER_SYNC_RELATION].relation_changed,
            self.on[CONTROLLER_SYNC_RELATION].relation_broken,
            self.on[LWS_SYNC_RELATION].relation_changed,
            self.on[LWS_SYNC_RELATION].relation_broken,
        ]:
            self.framework.observe(event, self._on_event)
        self.framework.observe(self.on.remove, self._on_remove)

        self.unit.set_ports(METRICS_PORT, METRICS_PROXY_PORT)
        self.prometheus_provider = MetricsEndpointProvider(
            self,
            jobs=[
                {
                    "job_name": "llmisvc-controller",
                    "static_configs": [{"targets": [f"*:{METRICS_PORT}"]}],
                },
                {
                    "job_name": "llmisvc-workload-aggregated",
                    "static_configs": [{"targets": [f"*:{METRICS_PROXY_PORT}"]}],
                },
            ],
        )

    @property
    def _context(self):
        """Render context for base resource templates."""
        ca_context = b64encode(self._stored.ca.encode("ascii"))
        return {
            "app_name": self.app.name,
            "namespace": self.model.name,
            "webhook_service_name": self._webhook_service_name,
            "cert": f"'{ca_context.decode('utf-8')}'",
        }

    @property
    def _scheduler_context(self):
        """Render context for scheduler config templates."""
        return {
            "namespace": self.model.name,
            "scheduler_image": self.images_context.get("llm_scheduler", ""),
            "workload_image": self.images_context.get("llm_workload", ""),
            "llm_routing_sidecar": self.images_context.get("llm_routing_sidecar", ""),
        }

    @property
    def base_resource_handler(self):
        """K8s handler for core llmisvc resources."""
        if not self._base_resource_handler:
            self._base_resource_handler = KubernetesResourceHandler(
                field_manager=self._lightkube_field_manager,
                template_files=BASE_RESOURCE_FILES,
                context=self._context,
                labels=create_charm_default_labels(
                    self.app.name, self.model.name, scope=KRH_SCOPE_BASE
                ),
                logger=log,
            )
        return self._base_resource_handler

    @property
    def scheduler_config_resource_handler(self):
        """K8s handler for scheduler-focused config resources."""
        if not self._scheduler_config_resource_handler:
            self._scheduler_config_resource_handler = KubernetesResourceHandler(
                field_manager=self._lightkube_field_manager,
                template_files=SCHEDULER_CONFIG_FILES,
                context=self._scheduler_context,
                labels=create_charm_default_labels(
                    self.app.name, self.model.name, scope=KRH_SCOPE_SCHEDULER_CONFIG
                ),
                logger=log,
            )
        return self._scheduler_config_resource_handler

    def _sync_handler_resource_types(self, handler: KubernetesResourceHandler):
        """Set handler.resource_types from its current rendered manifests."""
        # Register generic resources for CRDs currently present in-cluster before rendering.
        load_in_cluster_generic_resources(handler.lightkube_client)
        try:
            manifests = list(handler.render_manifests())
        except LoadResourceError as e:
            log.warning(
                "Skipping resource type sync for handler due to unresolved resource: %s", e
            )
            return []
        if manifests:
            handler.resource_types = {type(resource) for resource in manifests}
        return manifests

    @property
    def _metrics_proxy_pebble_layer(self):
        """Pebble layer for the metrics-k8s-proxy sidecar container.

        The proxy watches pods matching ``WORKLOAD_POD_LABEL_SELECTOR`` and
        exposes an aggregated ``/metrics`` endpoint on ``METRICS_PROXY_PORT``
        suitable for a Prometheus scrape job. Pods discovered by the proxy
        must carry the standard ``prometheus.io/scrape`` annotations.
        """
        return Layer(
            {
                "summary": "metrics-k8s-proxy layer",
                "description": "Aggregates Prometheus metrics from llmisvc workload pods",
                "services": {
                    METRICS_PROXY_CONTAINER: {
                        "override": "replace",
                        "summary": "metrics-k8s-proxy",
                        "command": "metrics-proxy",
                        "startup": "enabled",
                        "environment": {
                            "POD_LABEL_SELECTOR": WORKLOAD_POD_LABEL_SELECTOR,
                            "SCRAPE_TIMEOUT": METRICS_PROXY_SCRAPE_TIMEOUT,
                            "PORT": str(METRICS_PROXY_PORT),
                        },
                    },
                },
            }
        )

    @property
    def _controller_pebble_layer(self):
        """Pebble layer for llmisvc controller workload."""
        return Layer(
            {
                "services": {
                    self._controller_container_name: {
                        "override": "replace",
                        "summary": "KServe LLMInferenceService Controller",
                        "command": (
                            f"/manager --metrics-addr=:{METRICS_PORT} "
                            "--metrics-secure=false --leader-elect"
                        ),
                        "startup": "enabled",
                        "environment": {
                            "POD_NAMESPACE": self.model.name,
                        },
                        "on-check-failure": {
                            "llmisvc-controller-ready": "restart",
                            "llmisvc-controller-alive": "restart",
                        },
                    },
                },
                "checks": {
                    "llmisvc-controller-ready": {
                        "override": "replace",
                        "level": "ready",
                        "http": {"url": "http://localhost:8081/readyz"},
                    },
                    "llmisvc-controller-alive": {
                        "override": "replace",
                        "level": "alive",
                        "http": {"url": "http://localhost:8081/healthz"},
                    },
                },
            }
        )

    def _kserve_controller_is_ready(self) -> bool:
        """Return True when sync relation indicates kserve-controller is ready."""
        relation = self.model.get_relation(CONTROLLER_SYNC_RELATION)
        if relation is None or relation.app is None:
            return False

        app_data = relation.data.get(relation.app, {})
        ready = app_data.get("ready", "false").lower() == "true"
        return ready

    def _validate_kserve_controller_relation(self) -> None:
        """Validate relation presence and readiness from kserve-controller.

        Missing relation is a user-actionable misconfiguration (Blocked).
        Present relation without ready=true is a convergence state (Waiting).
        """
        relation = self.model.get_relation(CONTROLLER_SYNC_RELATION)
        if relation is None or relation.app is None:
            raise ErrorWithStatus(
                "Please relate to kserve-controller:kserve-controller",
                BlockedStatus,
            )

        if not self._kserve_controller_is_ready():
            raise ErrorWithStatus(
                "Waiting for relation to kserve-controller to report ready=true",
                WaitingStatus,
            )

    def _lws_controller_is_ready(self) -> bool:
        """Return True when sync relation indicates lws-controller is ready."""
        relation = self.model.get_relation(LWS_SYNC_RELATION)
        if relation is None or relation.app is None:
            return False

        app_data = relation.data.get(relation.app, {})
        return app_data.get("ready", "false").lower() == "true"

    def _validate_lws_controller_relation(self) -> None:
        """Validate relation presence and readiness from lws-controller.

        Missing relation is a user-actionable misconfiguration (Blocked).
        Present relation without ready=true is a convergence state (Waiting).
        """
        relation = self.model.get_relation(LWS_SYNC_RELATION)
        if relation is None or relation.app is None:
            raise ErrorWithStatus(
                "Please relate to lws-controller:lws-controller",
                BlockedStatus,
            )

        if not self._lws_controller_is_ready():
            raise ErrorWithStatus(
                "Waiting for relation to lws-controller to report ready=true",
                WaitingStatus,
            )

    def _on_event(self, event):
        """Main reconcile loop for llmisvc charm."""
        try:
            self._validate_kserve_controller_relation()
            self._validate_lws_controller_relation()

            self.custom_images = parse_images_config(self.model.config["custom_images"])
            self.images_context = self.get_images(DEFAULT_IMAGES, self.custom_images)

            self.unit.status = MaintenanceStatus("Creating k8s resources")

            self._sync_handler_resource_types(self.base_resource_handler)
            self._sync_handler_resource_types(self.scheduler_config_resource_handler)

            self.base_resource_handler.apply()

            self._upload_certs_to_container(
                container=self.controller_container,
                destination_path=CONTAINER_CERTS_DEST,
                certs_store=self._stored,
            )

            update_layer(
                self._controller_container_name,
                self.controller_container,
                self._controller_pebble_layer,
                log,
            )
            self._restart_controller_service()

            if self.metrics_proxy_container.can_connect():
                update_layer(
                    METRICS_PROXY_CONTAINER,
                    self.metrics_proxy_container,
                    self._metrics_proxy_pebble_layer,
                    log,
                )
            else:
                log.info("metrics-proxy container not reachable yet, skipping layer update")

            try:
                self.scheduler_config_resource_handler.apply()
                self.unit.status = ActiveStatus()
                log.info("llmisvc controller was ready. Applied all LLMInferenceServiceConfigs.")
            except ApiError as e:
                if e.status.code == 500 and "connect: " in e.status.message:
                    log.warning(
                        "Failed to create LLMInferenceServiceConfigs: %s", e.status.message
                    )
                    msg = (
                        "Charm Pod is not ready yet. Will apply LLMInferenceServiceConfigs later."
                    )
                    log.info(msg)
                    self.model.unit.status = MaintenanceStatus(msg)
                elif "no endpoints available" in e.status.message:
                    log.warning(
                        "Failed to create LLMInferenceServiceConfigs: %s", e.status.message
                    )
                    msg = "Webhook Server Service endpoints not ready. Will apply LLMInferenceServiceConfigs later."  # noqa: E501
                    log.info(msg)
                    self.model.unit.status = MaintenanceStatus(msg)
                else:
                    log.warning("Unexpected ApiError happened: %s", e)
                    raise GenericCharmRuntimeError(
                        f"Unexpected ApiError happened: {e.status.message}",
                    ) from e
        except ErrorWithStatus as err:
            self.model.unit.status = err.status
            log.error("Failed to handle %s with error: %s", event, err)
            return
        except ApiError:
            log.exception("Kubernetes API error during reconcile")
            raise

    @tenacity.retry(
        stop=tenacity.stop_after_delay(LLMISVC_DELETION_TIMEOUT),
        wait=tenacity.wait_fixed(LLMISVC_DELETION_POLL_INTERVAL),
        reraise=True,
    )
    def ensure_resource_is_deleted(self, client: Client, resource_kind, resource_name: str):
        """Block until a resource no longer exists, retrying on each check.

        Used to wait for the LLMInferenceService CRD to finish terminating.
        Deleting the CRD cascades deletion to all its CRs, whose finalizers are
        cleared by the still-running controller; the workload must not be torn
        down until that completes.

        Args:
            client: The lightkube client to use for talking to K8s.
            resource_kind: The lightkube resource class to check.
            resource_name: The name of the resource to check.

        Raises:
            ApiError: From lightkube, if there was an error aside from 404.
            ObjectStillExistsError: If the resource still exists after retries.
        """
        log.info("Checking if resource exists: %s", resource_name)
        try:
            client.get(resource_kind, name=resource_name)
            log.info('Resource "%s" exists, retrying...', resource_name)
            raise ObjectStillExistsError(resource_name)
        except ApiError as e:
            if e.status.code == 404:
                log.info('Resource "%s" does not exist!', resource_name)
                return
            # Raise any other error
            raise

    def _on_remove(self, _):
        """Delete resources rendered by llmisvc handlers."""
        self.unit.status = MaintenanceStatus("Removing k8s resources")

        base_manifests = self._sync_handler_resource_types(self.base_resource_handler)
        scheduler_has_manifests = bool(
            self._sync_handler_resource_types(self.scheduler_config_resource_handler)
        )

        client = self.base_resource_handler.lightkube_client
        try:
            # Delete the scheduler-config LLMInferenceServiceConfig CRs first,
            # while their CRD still exists. Once the CRDs are removed below the
            # serving.kserve.io API endpoints disappear and this handler can no
            # longer list its resources, so it must run before the CRD deletion.
            if scheduler_has_manifests:
                self.scheduler_config_resource_handler.delete(ignore_missing=True)

            # Delete the LLMInferenceService CRD next, while the controller is
            # still running. Removing the CRD cascades deletion to all its CRs
            # and the controller clears their finalizers. Block until the CRD is
            # fully gone before deleting anything else, otherwise the CRD (and
            # its CRs) would get stuck terminating once the controller workload
            # is torn down.
            crd_manifests = [
                resource
                for resource in base_manifests
                if isinstance(resource, CustomResourceDefinition)
            ]
            if crd_manifests:
                delete_many(client, crd_manifests, ignore_missing=True, logger=log)
                for crd in crd_manifests:
                    self.ensure_resource_is_deleted(
                        client=client,
                        resource_kind=CustomResourceDefinition,
                        resource_name=crd.metadata.name,
                    )

            # Finally delete the remaining base resources (webhooks, RBAC, the
            # already-removed CRDs). These are all standard Kubernetes resource
            # types whose API endpoints survive CRD deletion, so listing them
            # here is safe.
            if base_manifests:
                self.base_resource_handler.delete(ignore_missing=True)
        except ApiError as e:
            if e.status.code != 404:
                log.warning("Failed to delete resources with error: %s", e)
                raise
        except ObjectStillExistsError as e:
            log.warning(
                "Failed to remove resource: %s. Manual intervention for cleanup might be required",
                e.resource_name,
            )
            raise
        self.unit.status = MaintenanceStatus("K8s resources removed")

    def _gen_certs_if_missing(self) -> None:
        """Generate certs if they are not present in stored state."""
        log.info("Generating certificates if missing.")
        for cert_attribute in ["cert", "ca", "key"]:
            try:
                getattr(self._stored, cert_attribute)
                log.info("Certificate %s already exists, skipping generation.", cert_attribute)
            except AttributeError:
                self._gen_certs()
                return

    def _gen_certs(self):
        """Generate and persist self-signed certs for webhook server."""
        log.info("Generating certificates..")
        certs = gen_certs(
            service_name=self._controller_service_name,
            namespace=self.model.name,
            webhook_service=self._webhook_service_name,
        )
        for k, v in certs.items():
            setattr(self._stored, k, v)

    def _check_container_connection(self, container: Container) -> None:
        """Check if connection can be made with container.

        Raises:
            ErrorWithStatus if the connection cannot be made.
        """
        if not container.can_connect():
            raise ErrorWithStatus("Pod startup is not complete", MaintenanceStatus)

    def _upload_certs_to_container(
        self, container: Container, destination_path: str, certs_store: StoredState
    ) -> None:
        """Upload generated certs into workload container."""
        try:
            self._check_container_connection(container)
        except ErrorWithStatus as error:
            self.model.unit.status = error.status
            return

        try:
            container.push(f"{destination_path}/tls.key", certs_store.key, make_dirs=True)
            container.push(f"{destination_path}/tls.crt", certs_store.cert, make_dirs=True)
            container.push(f"{destination_path}/ca.crt", certs_store.ca, make_dirs=True)
        except (ProtocolError, PathError) as e:
            raise GenericCharmRuntimeError("Failed to push certs to container") from e

    def _restart_controller_service(self) -> None:
        """Restart controller service when container and service are available."""
        if not self.controller_container.can_connect():
            log.info("Skipping service restart, controller container is not reachable")
            return

        try:
            self.controller_container.get_service(self._controller_container_name).is_running()
        except ModelError:
            log.info("Service not found, nothing to restart")
            return

        try:
            self.controller_container.restart(self._controller_container_name)
            log.info("Restarted the controller pebble service")
        except APIError as err:
            raise GenericCharmRuntimeError(
                f"Failed to restart {self._controller_container_name} service"
            ) from err

    def get_images(
        self, default_images: Dict[str, str], custom_images: Dict[str, str]
    ) -> Dict[str, str]:
        """Merge default images with custom image overrides."""
        images = dict(default_images)
        for image_name, custom_image in custom_images.items():
            if custom_image:
                if image_name in images:
                    images[image_name] = custom_image
                else:
                    log.warning("image_name %s not in default image list, ignoring", image_name)
        return images


if __name__ == "__main__":
    main(KServeLLMISVCCharm)
