# reusable workflow triggered by other actions
name: CI

on:
  workflow_call:
    secrets:
      CHARMCRAFT_CREDENTIALS:
        required: true

jobs:
  lib-check:
    name: Check libraries
    strategy:
      matrix:
        charm:
        - kserve-controller
        - kserve-web-app
    uses: canonical/charmed-kubeflow-workflows/.github/workflows/_quality-checks.yaml@main
    secrets: inherit
    with:
        charm-path: ./charms/${{ matrix.charm }}

  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # TODO: add web-app once changes in canonical/kserve-operators#2 and #3
        # are merged. Not running web-app lint tests as the charm is still WIP.
        charm: [controller, web-app]
    steps:
    - uses: actions/checkout@v3
    - run: sudo apt update && sudo apt install tox
    - run: tox -e ${{ matrix.charm }}-lint

  unit:
    name: Unit Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # TODO: add web-app once changes in canonical/kserve-operators#2 and #3
        # are merged. Not running web-app lint tests as the charm is still WIP.
        charm: [controller]
    steps:
    - uses: actions/checkout@v3
    - run: sudo apt update && sudo apt install tox
    - run: tox -e ${{ matrix.charm }}-unit

  charm-integration:
    name: Individual Integration Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # TODO: add web-app once changes in canonical/kserve-operators#2 and #3
        # are merged. Not running web-app individual integration tests as
        # the charm is still WIP.
        charm: [controller]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          provider: microk8s
          channel: 1.25/stable
          # Pinned until this bug is resolved: https://bugs.launchpad.net/juju/+bug/1992833
          bootstrap-options: "--agent-version=2.9.34"
          charmcraft-channel: latest/candidate
      - run: tox -e ${{ matrix.charm }}-integration

      # On failure, capture debugging resources
      - name: Get all
        run: kubectl get all -A
        if: failure()

      - name: Describe deployments
        run: kubectl describe deployments -A
        if: failure()

      - name: Describe replicasets
        run: kubectl describe replicasets -A
        if: failure()

      - name: Get juju status
        run: juju status
        if: failure()

      - name: Get application logs
        run: kubectl logs -n testing --tail 1000 -ljuju-app=${{ matrix.charm }}
        if: failure()
