# reusable workflow triggered by other actions
name: Continuous Integration

on:
  workflow_call:
    secrets:
      charmcraft-credentials:
        required: true

jobs:

  lib-check:
    name: Check libraries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check libs
        uses: canonical/charming-actions/check-libraries@2.1.1
        with:
          credentials: "${{ secrets.charmcraft-credentials }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    strategy:
      matrix:
        charm: [controller, web-app]
    steps:
    - uses: actions/checkout@v3
    - run: sudo apt update && sudo apt install tox
    - run: tox -e ${{ matrix.charm }}-lint

  unit:
    name: Unit Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        charm: [controller, web-app]
    steps:
    - uses: actions/checkout@v3
    - run: sudo apt update && sudo apt install tox
    - run: tox -e ${{ matrix.charm }}-unit

  charm-integration:
    name: Individual Integration Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        charm: [controller, web-app]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          provider: microk8s
          channel: 1.24/stable
          charmcraft-channel: latest/candidate
      - run: tox -e ${{ matrix.charm }}-integration

      # On failure, capture debugging resources
      - name: Get all
        run: kubectl get all -A
        if: failure()

      - name: Describe deployments
        run: kubectl describe deployments -A
        if: failure()

      - name: Describe replicasets
        run: kubectl describe replicasets -A
        if: failure()

      - name: Get juju status
        run: juju status
        if: failure()

      - name: Get application logs
        run: kubectl logs -n testing --tail 1000 -ljuju-app=${{ matrix.charm }}
        if: failure()
