# reusable workflow triggered by other actions
name: CI

on:
  workflow_call:
    secrets:
      CHARMCRAFT_CREDENTIALS:
        required: true

jobs:
  lib-check:
    name: Check libraries
    strategy:
      matrix:
        charm:
        - kserve-controller
    uses: canonical/charmed-kubeflow-workflows/.github/workflows/_quality-checks.yaml@main
    secrets: inherit
    with:
        charm-path: ./charms/${{ matrix.charm }}

  lint:
    name: Lint Code
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        charm: [kserve-controller]
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: pipx install tox

    - run: tox -e ${{ matrix.charm }}-lint

  unit:
    name: Unit Test
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        charm: [kserve-controller]
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: pipx install tox

    - run: tox -e ${{ matrix.charm }}-unit

  terraform-checks:
    name: Terraform
    uses: canonical/charmed-kubeflow-workflows/.github/workflows/terraform-checks.yaml@main
    with:
      charm-path: ./charms/kserve-controller

  charm-integration:
    name: Individual Integration Tests
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        charm: [kserve-controller]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: pipx install tox

      - name: Setup environment
        run: |
          sudo apt-get remove -y docker-ce docker-ce-cli containerd.io
          sudo rm -rf /run/containerd
          sudo snap install concierge --classic
          sudo concierge prepare --trace

      - name: Get all
        run: kubectl get all -A
        if: failure()

      - name: Get inference servers
        run: kubectl get inferenceservices -A
        if: failure()

      - name: Get events
        run: kubectl get events -A
        if: failure()

      - name: Describe deployments
        run: kubectl describe deployments -A
        if: failure()

      - name: Describe replicasets
        run: kubectl describe replicasets -A
        if: failure()

      - name: Get juju status
        run: juju status
        if: failure()

      - name: Get application logs
        run: kubectl logs -n testing --tail 1000 -ljuju-app=${{ matrix.charm }}
        if: failure()
