# reusable workflow triggered by other actions
name: CI

on:
  workflow_call:
    secrets:
      CHARMCRAFT_CREDENTIALS:
        required: true

jobs:
  lib-check:
    name: Check libraries
    strategy:
      matrix:
        charm:
        - kserve-controller
    uses: canonical/charmed-kubeflow-workflows/.github/workflows/_quality-checks.yaml@main
    secrets: inherit
    with:
        charm-path: ./charms/${{ matrix.charm }}

  lint:
    name: Lint Code
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        charm: [controller]
    steps:
    - uses: actions/checkout@v3
    - run: sudo apt update && sudo apt install tox
    - run: tox -e ${{ matrix.charm }}-lint

  unit:
    name: Unit Test
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        charm: [controller]
    steps:
    - uses: actions/checkout@v3
    - run: sudo apt update && sudo apt install tox
    - run: tox -e ${{ matrix.charm }}-unit

  charm-integration:
    name: Individual Integration Tests
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        charm: [controller]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          provider: microk8s
          channel: 1.25-strict/stable
          juju-channel: 3.1/stable
          microk8s-addons: "dns storage rbac metallb:10.64.140.43-10.64.140.49"
          charmcraft-channel: latest/candidate
      - run: |
          juju add-model kubeflow --config default-series=focal --config automatically-retry-hooks=true
          tox -e ${{ matrix.charm }}-integration -- --model kubeflow -vv -s

      - name: Save relevant debug artifacts
        if: always()
        run: |
          mkdir ~/kfp-operators-debug-logs
          juju debug-log --replay | tee ~/kfp-operators-debug-logs/juju-debug-log.log
          juju status | tee ~/kfp-operators-debug-logs/juju-status.log
          microk8s.kubectl describe pods -A | tee ~/kfp-operators-debug-logs/pods.log
          microk8s.kubectl get configmaps -A | tee ~/kfp-operators-debug-logs/cm.log

      - name: Upload debug artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: kfp-operators-debug-logs
          path: ~/kfp-operators-debug-logs

      - name: Setup upterm session
        uses: lhotari/action-upterm@v1

      - name: Get all
        run: kubectl get all -A
        if: failure()

      - name: Get inference servers
        run: kubectl get inferenceservices -A
        if: failure()

      - name: Get events
        run: kubectl get events -A
        if: failure()

      - name: Describe deployments
        run: kubectl describe deployments -A
        if: failure()

      - name: Describe replicasets
        run: kubectl describe replicasets -A
        if: failure()

      - name: Get juju status
        run: juju status
        if: failure()

      - name: Get application logs
        run: kubectl logs -n testing --tail 1000 -ljuju-app=${{ matrix.charm }}
        if: failure()
