# reusable workflow triggered by other actions
name: Publish

on:
  workflow_call:
    secrets:
      charmcraft-credentials:
        required: true

jobs:

  publish-charm:
    name: Publish Charm
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        charm:
          - kserve-web-app
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Select charmhub channel
        uses: canonical/charming-actions/channel@2.1.1
        id: channel
      - name: Upload charm to charmhub
        uses: canonical/charming-actions/upload-charm@2.1.1
        with:
          credentials: ${{ secrets.charmcraft-credentials }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          charm-path: charms/${{ matrix.charm }}
          channel: ${{ steps.channel.outputs.name }}
          tag-prefix: ${{ matrix.charm }}
