name: LLMInferenceService testbed

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'branch name'
        required: true
        default: 'llmisvc-rewrite'
        type: string
  push:
    branches: [ llmisvc-rewrite ] # to fix when merged to main
  pull_request:

jobs:
  testflinger-vs:
    runs-on: [self-hosted, self-hosted-linux-amd64-jammy-private-endpoint-medium]
    timeout-minutes: 1440   # Time limit for this GitHub workflow job (not testflinger job!): 24 hours
    steps:
      - uses: actions/checkout@v7

      - name: Generate job YAML
        uses: cuchi/jinja2-action@v1.3.0
        with:
          template: ${{ github.workspace }}/.github/testflinger/job.yaml.j2
          output_file: tmp_job.yaml
          strict: true
          variables: |
            branch=${{ github.head_ref || github.ref_name }}

      - name: Check job yaml
        run: |
          # Copy to solve the file permission issue
          cp tmp_job.yaml job.yaml
          cp  ${{ github.workspace }}/.github/testflinger/concierge.yaml concierge.yaml
          ls -al job.yaml
          ls -al concierge.yaml
          cat job.yaml
          cat concierge.yaml

      - name: Submit job
        id: submit-job
        uses: canonical/testflinger/.github/actions/submit@main
        with:
          poll: true
          job-path: job.yaml
          client-id: ${{ secrets.TESTFLINGER_CLIENT_ID }}
          client-secret: ${{ secrets.TESTFLINGER_SECRET_KEY }}

      - name: Display results
        id: get-results
        run: |
          testflinger results ${{ steps.submit-job.outputs.id }} > results.json
          cat results.json

      # - name: Check test status
      #   run: |
      #     set -e
      #     testflinger results ${{ steps.submit-job.outputs.id }} > results.json
      #     status=$(jq '.test_status' results.json)
      #     if ! [[ "$status" =~ ^[0-9]+$ ]]; then
      #       echo "Invalid or missing test_status in results.json"
      #       exit 1
      #     fi
      #     if [ "$status" -ne 0 ]; then
      #         echo "testflinger task failed with status $status"
      #         jq -r '.test_output' results.json
      #         exit 1
      #     else
      #         echo "testflinger task succeeded"
      #     fi